FROM n8nio/n8n

ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV WEBHOOK_URL=https://n8n-docker-render-1.onrender.com/
ENV N8N_ALLOW_ORIGINS=https://factupos.co
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=dpg-cvu2fqq4d50c73apf8t0-a.oregon-postgres.render.com
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=n8n_3zik
ENV DB_POSTGRESDB_USER=n8nuser
ENV DB_POSTGRESDB_PASSWORD=f8JnUTQRySfKsm0EQycgbktld8R42u6v
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
ENV N8N_USER_MANAGEMENT_DISABLED=true

ENTRYPOINT ["tini", "--"]
CMD ["n8n"]
EXPOSE 5678
