services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true

    # El puerto interno que expone n8n
    ports:
      - 5678

    # Volumen para persistencia de datos
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1

    # Variables de entorno definidas en Render (sobrescriben las del Dockerfile si difieren)
    envVars:
      # Configuración básica del servidor n8n
      - key: N8N_ENCRYPTION_KEY
        value: fA7t9kV!x83pGdS62rBQzMTY*LrA1u!v
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: WEBHOOK_URL
        value: "https://n8n-docker-render-1.onrender.com"
      - key: N8N_ENDPOINT_WEBHOOK
        value: "/webhook"
      - key: N8N_ENDPOINT_WEBHOOK_TEST
        value: "/webhook-test"

      # Habilitar CORS
      - key: N8N_CORS_ENABLED
        value: "true"
      - key: N8N_CORS_ALLOWED_ORIGINS
        value: "https://factupos.co"
      - key: N8N_CORS_ALLOWED_METHODS
        value: "GET,POST,OPTIONS"
      - key: N8N_CORS_ALLOWED_HEADERS
        value: "Content-Type,Authorization"
      - key: N8N_CORS_ALLOW_CREDENTIALS
        value: "false"

      # Autenticación básica
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "admin123"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "true"

      # Configuración de la base de datos PostgreSQL
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "dpg-cvuf0eq4d50c73au6ma0-a.oregon-postgres.render.com"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "n8n_data_3vbl"
      - key: DB_POSTGRESDB_USER
        value: "n8nuser"
      - key: DB_POSTGRESDB_PASSWORD
        value: "tFpfmTSvsik91mUSWHQhh8552W0qYD2N"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
