services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    ports:
      - 5678
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      # Variables necesarias para la conexión a la base de datos
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "dpg-cvuf0eq4d50c73au6ma0-a.oregon-postgres.render.com"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "n8n_data_3vbl"
      - key: DB_POSTGRESDB_USER
        value: "n8nuser"
      - key: DB_POSTGRESDB_PASSWORD
        value: "tFpfmTSvsik91mUSWHQhh8552W0qYD2N"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
